apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  creationTimestamp: null
  labels:
    app: my-websitev1
  name: my-websitev1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-websitev1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-websitev1
    spec:
      containers:
      - image: {{ .Values.image }}
        name: v1
        resources: {}
status: {}
