apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-website
  name: my-website
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-website
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-website
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
