apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-websitev1
    app.kubernetes.io/managed-by: Helm
  name: my-websitev1
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: my-websitev1
status:
  loadBalancer: {}
